name: Laravel CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: systeme_dep_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: none
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction
          cp .env.example .env
          php artisan key:generate
      - name: Execute tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: systeme_dep_test
          DB_USERNAME: root
          DB_PASSWORD: password
        run: |
          php artisan migrate:fresh --env=testing
          php artisan db:seed --env=testing
          php artisan test
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deployment to production would happen here"
